device: "cuda"

image_size:
  height: 128
  width: 128

depth_range:
  max: 60.569854736328125
  min: 7.274515628814697

num_diffusion_frames: 10
dataset_dir: "data/peract_processed_dataset"

## 3DUNet parameters
unet:
  dim: 64
  dim_mults: [1, 2, 4, 8]
  in_channels: 1
  out_channels: 1
  attn_heads: 8
  attn_dim_head: 32

encoder:
  text_embedding_dim: 512
  image_embedding_dim: 512
  global_embedding_dim: 512

training:
  batch_size: 4
  shuffle: True
  num_workers: 4
  pin_memory: True
  persistent_workers: True
  learning_rate: 1e-4
  weight_decay: 1e-5
  num_warmup_steps: 500
  num_epochs: 10000

diffusion:
  num_timesteps: 1000