device: "cuda"

image_size:
  height: 128
  width: 128

depth_range:
  max: 60.569854736328125
  min: 7.274515628814697

num_diffusion_frames: 16

## 3DUNet parameters
unet:
  dim: 64
  dim_mults: [1, 2, 4]
  in_channels: 1
  out_channels: 1
  attn_heads: 8
  attn_dim_head: 32

encoder:
  text_embedding_dim: 512
  image_embedding_dim: 512
  global_embedding_dim: 256